eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: test-order
env:
  dev
girl:
  name: 李勃昊和李伦-我是女孩~我我问问
  age: 今年25,我会唱跳rap篮球~!aaaaaaaaaaaaa
